name: Build main
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install
        run: npm ci
      - name: Test
        run: npm test

